spring: 
    profiles: 
        active:
        - dev
---
spring: 
    profiles: dev
    application:
        name: microservicecloud-config-happy-dev
---
spring: 
    profiles: test
    application:
        name: microservicecloud-config-happy-test

